spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 198964
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
logging:
  level:
    root: info
    com.gzj: debug
  file: log/blog-dev.log